#1. Load Data

In [4]:
#Import Library
import pandas as pd

In [5]:
#Read data
df=pd.read_csv('Copy of telco_customer_churn.csv')

In [6]:
pd.DataFrame

pandas.core.frame.DataFrame

In [7]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

#2. Tipe Data

In [8]:
#Menunjukkan jenis data pada setiap kolom

df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

#3. Rename Kolom

In [9]:
#Rename column customerID menjadi CustID
df=df.rename(columns={'customerID':'CustID'})

In [10]:
#Menampilkan hasil setelah di rename
df

,CustID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
#Mengubah semua column menjadi lowercase
df.columns=df.columns.str.lower()

In [13]:
#Membaca data setelah diberikan command lowercase
df

,custid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

#4. Data Cleaning: Hilangkan "Automatic" pada Payment Method

In [14]:
#Menghilangkan kata automatic pada kolom Payment Method

df['paymentmethod']=df['paymentmethod'].str.replace('(automatic)','')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

In [15]:
df['paymentmethod']

0       Electronic check
1           Mailed check
2           Mailed check
3       Bank transfer ()
4       Electronic check
              ...
7038        Mailed check
7039      Credit card ()
7040    Electronic check
7041        Mailed check
7042    Bank transfer ()
Name: paymentmethod, Length: 7043, dtype: object

In [16]:
#Menghilangkan tanda '()' pada payment method

df['paymentmethod']=df['paymentmethod'].str.replace('()','',regex=False)

In [14]:
#Melakukan pengecekan kembali hasil command
df['paymentmethod']

0       Electronic check
1           Mailed check
2           Mailed check
3         Bank transfer
4       Electronic check
              ...
7038        Mailed check
7039        Credit card
7040    Electronic check
7041        Mailed check
7042      Bank transfer
Name: paymentmethod, Length: 7043, dtype: object

In [17]:
#menghilangkan karakter spasi diawal dan diakhir kalimat pada payment method (menggunakan fungsi strip)
df['paymentmethod']=df['paymentmethod'].str.strip()

In [18]:
df

,custid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer,42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card,103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer,105.65,6844.5,No

#5. Data Processing

a. One-Hot Encoding

In [19]:
#membuat one-hot encoding pada kolom phoneservice dengan prefiks=serviced
encorder_phoneservice=pd.get_dummies(df,
               columns=['phoneservice'],
               prefix='service')

In [20]:
encorder_phoneservice

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.5,No,0,1
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,1
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,No,One year,No,Bank transfer,42.30,1840.75,No,1,0
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,DSL,Yes,No,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,0,1
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,...,Yes,Yes,One year,Yes,Credit card,103.20,7362.9,No,0,1
7040,4801-JZAZL,Female,0,Yes,Yes,11,No phone service,DSL,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,1,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,0,1
7042,3186-AJIEK,Male,0,No,No,66,No,Fiber optic,Yes,No,...,Yes,Yes,Two year,Yes,Bank transfer,105.65,6844.5,No,0,1

In [21]:
#define encorder_phoneservice kedalam dataframe
df=encorder_phoneservice

In [22]:
df

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.5,No,0,1
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,1
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,No,One year,No,Bank transfer,42.30,1840.75,No,1,0
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,DSL,Yes,No,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,0,1
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,...,Yes,Yes,One year,Yes,Credit card,103.20,7362.9,No,0,1
7040,4801-JZAZL,Female,0,Yes,Yes,11,No phone service,DSL,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,1,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,0,1
7042,3186-AJIEK,Male,0,No,No,66,No,Fiber optic,Yes,No,...,Yes,Yes,Two year,Yes,Bank transfer,105.65,6844.5,No,0,1

b. Normalization

In [23]:
#Membuat Normalization untuk kolom monthlycharges
#Import library untuk Normalization

from sklearn.preprocessing import MinMaxScaler

In [24]:
df['monthlycharges']

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: monthlycharges, Length: 7043, dtype: float64

In [25]:
#define min max scaler
min_max_scaler=MinMaxScaler()

In [26]:
#melakukan normalization pada kolom monthlycharges
df['monthlycharges']=min_max_scaler.fit_transform(df[['monthlycharges']])

In [27]:
df['monthlycharges']

0       0.115423
1       0.385075
2       0.354229
3       0.239303
4       0.521891
          ...
7038    0.662189
7039    0.845274
7040    0.112935
7041    0.558706
7042    0.869652
Name: monthlycharges, Length: 7043, dtype: float64

In [28]:
#mengecek apakah normalization pada monthlycharges sudah diterapkan pada dataframe
df

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,0.115423,29.85,No,1,0
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,0.385075,1889.5,No,0,1
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,No,Month-to-month,Yes,Mailed check,0.354229,108.15,Yes,0,1
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,No,One year,No,Bank transfer,0.239303,1840.75,No,1,0
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Electronic check,0.521891,151.65,Yes,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,DSL,Yes,No,...,Yes,Yes,One year,Yes,Mailed check,0.662189,1990.5,No,0,1
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,...,Yes,Yes,One year,Yes,Credit card,0.845274,7362.9,No,0,1
7040,4801-JZAZL,Female,0,Yes,Yes,11,No phone service,DSL,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,0.112935,346.45,No,1,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Mailed check,0.558706,306.6,Yes,0,1
7042,3186-AJIEK,Male,0,No,No,66,No,Fiber optic,Yes,No,...,Yes,Yes,Two year,Yes,Bank transfer,0.869652,6844.5,No,0,1

c. Standarization

In [29]:
#Standarization untuk kolom totalcharge
#import library standarization

from sklearn.preprocessing import StandardScaler

In [30]:
#define standard scaler
Std_scaler=StandardScaler()

In [31]:
#melihat jenis data pada kolom totalcharges, hasil command, data bersifat object, bukan float. maka harus di cleaning dulu
df['totalcharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: totalcharges, Length: 7043, dtype: object

In [32]:
#mengecek data mulai index berapa yang sifatnya tidak float

row=0
for entry in df['totalcharges']:
  print(row)
  float(entry)
  row += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488

ValueError: ignored

result: menunjukkan mulai index 488 program berhenti. sekarang kita cek isi dari total charge baris 488

In [32]:
#cek index 488

df.loc[488]['totalcharges']

' '

resul: index 488 data bukan berupa number (float) namun berupa spasi

In [33]:
#mengecek index berapa saja yang bukan float. True=index yang bersifat float, False=bukan float

def isnumber(x):
  try:
    float(x)
    return True
  except:
    return False

df['isnumber']=df['totalcharges'].apply(isnumber)
index_isnotnumber=df[~df['isnumber']].index

In [38]:
#mengecek index yang isinya False (data bukan float) ada di index mana saja
df[~df['isnumber']]

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes,isnumber
488,4472-LVYGI,Female,0,Yes,Yes,0,No phone service,DSL,Yes,No,...,No,Two year,Yes,Bank transfer,0.341294,,No,1,0,False
753,3115-CZMZD,Male,0,No,Yes,0,No,No,No internet service,No internet service,...,No internet service,Two year,No,Mailed check,0.019900,,No,0,1,False
936,5709-LVOEQ,Female,0,Yes,Yes,0,No,DSL,Yes,Yes,...,Yes,Two year,No,Mailed check,0.622886,,No,0,1,False
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,No,No internet service,No internet service,...,No internet service,Two year,No,Mailed check,0.074627,,No,0,1,False
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No phone service,DSL,Yes,Yes,...,No,Two year,No,Credit card,0.376119,,No,1,0,False
3331,7644-OMVMY,Male,0,Yes,Yes,0,No,No,No internet service,No internet service,...,No internet service,Two year,No,Mailed check,0.015920,,No,0,1,False
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,No,No internet service,No internet service,...,No internet service,Two year,No,Mailed check,0.070647,,No,0,1,False
4380,2520-SGTTA,Female,0,Yes,Yes,0,No,No,No internet service,No internet service,...,No internet service,Two year,No,Mailed check,0.017413,,No,0,1,False
5218,2923-ARZLG,Male,0,Yes,Yes,0,No,No,No internet service,No internet service,...,No internet service,One year,Yes,Mailed check,0.014428,,No,0,1,False
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,DSL,No,Yes,...,No,Two year,No,Mailed check,0.548259,,No,0,1,False
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,DSL,Yes,Yes,...,No,Two year,Yes,Bank transfer,0.434328,,No,0,1,False

In [34]:
#fill totalcharges not number dengan median
#cari median totalcharges
median=df[df['isnumber']]['totalcharges'].astype('float64').median()

In [35]:
#membaca hasil median
median

1397.475

In [36]:
#mengubah 11 data pada variabel totalcharges dengan menggunakan median
df.loc[index_isnotnumber,'totalcharges']= median

In [37]:
#mengecek kembali apakah sudah berganti menjadi float
df.loc[index_isnotnumber].dtypes

custid               object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
service_No            uint8
service_Yes           uint8
isnumber               bool
dtype: object

In [38]:
#hasil diatas ternyata variable totalcharges belum berubah menjadi float
#maka,
#memgubah variable totalcharges menjadi data float
df['totalcharges']=df['totalcharges'].astype('float64')

In [41]:
#melakukan pengecekan kembali, apakah variable totalcharges sudah berganti menjadi data yang bersifat float
df.dtypes

custid               object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                object
service_No            uint8
service_Yes           uint8
isnumber               bool
dtype: object

In [40]:
df

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes,isnumber
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,0.115423,29.85,No,1,0,True
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,One year,No,Mailed check,0.385075,1889.50,No,0,1,True
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,0.354229,108.15,Yes,0,1,True
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer,0.239303,1840.75,No,1,0,True
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,0.521891,151.65,Yes,0,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,DSL,Yes,No,...,Yes,One year,Yes,Mailed check,0.662189,1990.50,No,0,1,True
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,...,Yes,One year,Yes,Credit card,0.845274,7362.90,No,0,1,True
7040,4801-JZAZL,Female,0,Yes,Yes,11,No phone service,DSL,Yes,No,...,No,Month-to-month,Yes,Electronic check,0.112935,346.45,No,1,0,True
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Fiber optic,No,No,...,No,Month-to-month,Yes,Mailed check,0.558706,306.60,Yes,0,1,True
7042,3186-AJIEK,Male,0,No,No,66,No,Fiber optic,Yes,No,...,Yes,Two year,Yes,Bank transfer,0.869652,6844.50,No,0,1,True

In [42]:
#Define Standard Scaler
Std_scaler=StandardScaler()

In [43]:
#Standarization untuk variable totalcharges
df['totalcharges']=Std_scaler.fit_transform(df[['totalcharges']])

In [44]:
#melakukan pengecekan kembali pada data pada variable totalcharges, apakah sudah ter-standarization atau belum.
df

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes,isnumber
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,0.115423,-0.994242,No,1,0,True
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,One year,No,Mailed check,0.385075,-0.173244,No,0,1,True
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,0.354229,-0.959674,Yes,0,1,True
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer,0.239303,-0.194766,No,1,0,True
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,0.521891,-0.940470,Yes,0,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,DSL,Yes,No,...,Yes,One year,Yes,Mailed check,0.662189,-0.128655,No,0,1,True
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,...,Yes,One year,Yes,Credit card,0.845274,2.243151,No,0,1,True
7040,4801-JZAZL,Female,0,Yes,Yes,11,No phone service,DSL,Yes,No,...,No,Month-to-month,Yes,Electronic check,0.112935,-0.854469,No,1,0,True
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Fiber optic,No,No,...,No,Month-to-month,Yes,Mailed check,0.558706,-0.872062,Yes,0,1,True
7042,3186-AJIEK,Male,0,No,No,66,No,Fiber optic,Yes,No,...,Yes,Two year,Yes,Bank transfer,0.869652,2.014288,No,0,1,True

DONE!!
GOOD LUCK!